### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by karteek-paruchuri** [zooba/projectoxford#12]
Hi 

I'm trying to run this code on Azure ubuntu 14.10 vm.
I installed pip (pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7))
Now when i try "sudo pip install projectoxford" 
I get the following output
Downloading/unpacking projectoxford
  Downloading projectoxford-0.3.1.zip
  Running setup.py (path:/tmp/pip_build_root/projectoxford/setup.py) egg_info for package projectoxford
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/projectoxford/setup.py", line 12, in <module>
        with open('README', 'r', encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/projectoxford/setup.py", line 12, in <module>

```
with open('README', 'r', encoding='utf-8') as f:
```

TypeError: 'encoding' is an invalid keyword argument for this function

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/projectoxford
Storing debug log for failure in /home/kparuchuri/.pip/pip.log

Can you please help me out. 

Thanks

**Comment by jacobjelen** [comment]
I'm having the same issue. Did you find a solution? 
thx

EDIT: Fixed it by writing `pip install projectoxford` 
Having both Python 2.7 and 3.5 versions installed seemed to be the issue. This library is supposed to run on 3.5 so to direct the installation to the right place you need to use `pip3`

The ReadMe.rtf in Python 2.7 says: 

> Python 3 and Python 2 Co-existence
> 
> Python.org Python 2.7 and 3.x versions can both be installed on your system and will not conflict.  Python 2.7 command names contain a 2 or no digit: python2 (or python2.7 or python), idle2 (or idle2.7 or idle), pip2 (or pip2.7 or pip), etc.  Command names for Python 3 contain a 3 in them, python3, idle3, pip3, etc.

**Comment by davidkinnes** [comment]
Know problem in Weasyprint : Kozea/WeasyPrint#323
Just need to upgrade Weasyprint to version 0.29 that fixes it.
